### PR TITLE
Lazy substitution

### LINKED ISSUE #1615: The pipeline::asm::reparse tests are horribly slow
re-parsing a single.asm file takes 5 seconds on my machine, there has to be something seriously wrong.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #1615

### CODE REVIEW

File: pil-analyzer/src/type_unifier.rs [hunk 1]
```diff
@@ -127,22 +110,32 @@ impl Unifier {
...
                 "Cannot unify types {ty} and {type_var}: They depend on each other"
             ));
         }
-        let subs = [(type_var.clone(), ty.clone())].into();
 
         for bound in self.type_var_bounds(&type_var) {
             self.ensure_bound(&ty, bound)?;
         }
 
-        self.substitutions
```
Comment (chriseth) [inline pil-analyzer/src/type_unifier.rs:142]: Who could have thought that it is bad for performance to iterate over all substitutions whenever a new one is added?

File: pil-analyzer/src/type_unifier.rs [hunk 2]
```diff
@@ -120,28 +103,38 @@ impl Unifier {
...
         self.type_var_bounds
             .entry(type_var)
             .or_default()
             .insert(bound);
     }
 
-    fn add_substitution(&mut self, type_var: String, ty: Type) -> Result<(), String> {
+    fn add_substitution(&mut self, type_var: String, mut ty: Type) -> Result<(), String> {
+        self.substitute(&mut ty);
+        //        println!("Adding substitution: {type_var} -> {ty}");
```
Comment (leonardoalt) [inline pil-analyzer/src/type_unifier.rs:127]: leftover

**Review by leonardoalt — APPROVED** [review]
