### PR TITLE
Witgen: Don't derive non-unique witness when there might be overflow

### LINKED ISSUE #593: Witgen does not detect soundness bug
In #570, I implemented a machine that wraps an arbitrary field element. It has a section that ensures soundness by preventing that the provided byte decomposition does not overflow. However, you can just remove it and witgen will generate the same witness (non-malicious) witness, where actually it should fail, because things are not unique.

### PR DESCRIPTION
**Pull request by georgwiese**
Fixes #593

### CODE REVIEW

File: executor/src/witgen/affine_expression.rs [hunk 1]
```diff
@@ -382,6 +384,12 @@ where
             offset &= !mask;
         }
 
+        if covered_bits > T::modulus() {
+            return Ok(EvalValue::incomplete(
+                IncompleteCause::OverflowingBitConstraints,
+            ));
+        }
```
Comment (georgwiese) [inline executor/src/witgen/affine_expression.rs:391]: This is the main fix.

File: std/split/split_bn254.asm [hunk 2]
```diff
@@ -15,7 +15,7 @@ machine SplitBN254(RESET, _) {
     // previous block)
     // A hint is provided because automatic witness generation does not
     // understand step 3 to figure out that the byte decomposition is unique.
-    let select_byte: fe, int -> fe = |input, byte| std::convert::fe((std::convert::int(input) >> (byte * 8)) % 0xff);
+    let select_byte: fe, int -> fe = |input, byte| std::convert::fe((std::convert::int(input) >> (byte * 8)) & 0xff);
```
Comment (georgwiese) [inline std/split/split_bn254.asm:18]: This was merged already in #1167, so this diff will disappear after a rebase / merge

File: std/split/split_gl.asm [hunk 3]
```diff
@@ -15,7 +15,7 @@ machine SplitGL(RESET, _) {
     // previous block)
     // A hint is provided because automatic witness generation does not
     // understand step 3 to figure out that the byte decomposition is unique.
-    let select_byte: fe, int -> fe = |input, byte| std::convert::fe((std::convert::int(input) >> (byte * 8)) % 0xff);
+    let select_byte: fe, int -> fe = |input, byte| std::convert::fe((std::convert::int(input) >> (byte * 8)) & 0xff);
```
Comment (georgwiese) [inline std/split/split_gl.asm:18]: Same here

File: executor/src/witgen/affine_expression.rs [hunk 4]
```diff
@@ -234,10 +234,13 @@ where
         }
     }
 
+    /// Solves equations of the form `dividend = divisor * quotient + remainder`
+    /// where `divident` and `divisor` are known and `remainder` is range-constrained to be smaller than `divisor`.
```
Comment (chriseth) [inline executor/src/witgen/affine_expression.rs:238]:
```suggestion
    /// where `dividend` and `divisor` are known and `remainder` is range-constrained to be smaller than `divisor`.
```

**Review by chriseth — APPROVED** [review]

File: executor/src/witgen/affine_expression.rs (hunk 1 above)
Comment (chriseth) [reply executor/src/witgen/affine_expression.rs:391]: Wait, why not `>= T::modulus()`? It probably does not matter since modulus + 1 is never a power of two

File: executor/src/witgen/affine_expression.rs (hunk 4 above)
Comment (georgwiese) [reply executor/src/witgen/affine_expression.rs:238]: 🤑

File: executor/src/witgen/affine_expression.rs (hunk 1 above)
Comment (georgwiese) [reply executor/src/witgen/affine_expression.rs]: True though!

**Comment by georgwiese** [comment]
Merged the most recent version of `sound-mul` (which has the most recent version of `main`)

**Review by chriseth — DISMISSED** [review]
please squash

**Review by chriseth — APPROVED** [review]
