### PR TITLE
`split_pil`: Put public declarations into the correct namespace

### LINKED ISSUE #1588: `CompositeBackend` does not work well with publics
Leo had to remove the public declarations from the RISC-V machine in #1583. I think the problem is related to them showing up in a separate namespace (the empty namespace), so they are merged with all machines, potentially referencing columns that don't exist.

### PR DESCRIPTION
**Pull request by georgwiese**
Fixes #1588

To test, you can run [Leo's example](https://gist.github.com/leonardoalt/7ba8071d9ac98f1b4e06f5b5c0d81f6b) (with `--prove-with plonky3`). The proof doesn't verify, but that appears to be a separate issue.

### CODE REVIEW

File: backend-utils/src/lib.rs [hunk 1]
```diff
@@ -171,17 +171,30 @@ fn split_by_namespace<F: FieldElement>(
...
     let mut current_namespace = "".to_string();
 
+    // Publics end up in the empty namespace, but we can find the correct namespace by looking
+    // at the referenced polynomial.
+    let public_to_namespace = pil
+        .public_declarations
+        .iter()
+        .map(|(public_name, public)| {
+            let ns = extract_namespace(&public.polynomial.name);
+            (public_name.clone(), ns)
```
Comment (Schaeff) [inline backend-utils/src/lib.rs:181]:
```suggestion
            (public_name, ns)
```

checked locally, works

**Review by Schaeff — APPROVED** [review]

File: backend-utils/src/lib.rs (hunk 1 above)
Comment (georgwiese) [reply backend-utils/src/lib.rs:181]: Oh, didn't see! But looks like we'll revert anyway after #2050 ;)
