### PR TITLE
Fix: PILAnalyzer::Children visits Trait functions twice

### LINKED ISSUE #1964: PILAnalyzer::Children visits Trait functions twice
I think PILAnalyzer::Children visits trait functions twice, once via the trait declaration and once via the individual trait functions.
The other problem here is that we store full copies, we should think about using Arcs instead.

### PR DESCRIPTION
**Pull request by gzanitti**
Fix #1964

### CODE REVIEW

File: ast/src/analyzed/mod.rs [hunk 1]
```diff
@@ -761,7 +761,7 @@ pub enum FunctionValueDefinition {
     Expression(TypedExpression),
     TypeDeclaration(TypeDeclaration),
     TypeConstructor(Arc<EnumDeclaration>, EnumVariant),
-    TraitDeclaration(TraitDeclaration),
+    TraitDeclaration(Arc<TraitDeclaration>),
```
Comment (chriseth) [inline ast/src/analyzed/mod.rs:764]: Do you nee the arc?

Comment (chriseth) [reply ast/src/analyzed/mod.rs:764]: In that case, please make sure you don't create a new Arc when constructing TraitFunctions, but clone the one form the declaration.

Comment (chriseth) [reply ast/src/analyzed/mod.rs:764]: Maybe it would be good to create  a function that creates a TraitFunction from a TraitDeclaration.

Comment (chriseth) [reply ast/src/analyzed/mod.rs]: Yes, great idea!

**Review by chriseth — APPROVED** [review]
