### PR TITLE
Remove leftover code relating to bus field assignments.

### LINKED ISSUE #2980: Bus field assignments do not work properly when bus interactions are removed from the system.

### PR DESCRIPTION
**Pull request by chriseth**
Closes #2980

### CODE REVIEW

File: constraint-solver/src/solver/quadratic_equivalences.rs [hunk 1]
```diff
@@ -36,6 +36,8 @@ pub fn find_quadratic_equalities<T: RuntimeConstant, V: Ord + Clone + Hash + Eq
 /// determined by a (the same) conditional assignment from
 /// `expr` or `expr + offset` (see [`QuadraticSymbolicExpression::solve_quadratic`]),
 /// then `X` and `Y` must be equal and are returned.
+///
+/// X
```
Comment (georgwiese) [inline constraint-solver/src/solver/quadratic_equivalences.rs]: ?

Comment (chriseth) [reply constraint-solver/src/solver/quadratic_equivalences.rs]: Ah sorry, will remove.

Comment (chriseth) [inline constraint-solver/src/solver/quadratic_equivalences.rs]:
```suggestion
```
